"""
This file contains the prompt templates for the therapeutic training task.
Created by Alexey Obukhov, alexey.obukhov@hotmail.com, 2025 Dresden

Purpose:
The `prompt_templates` dictionary provides various templates for generating therapeutic responses. These templates
are designed to guide the language model in generating relevant and helpful responses during a therapy session.
Each template is tailored to a specific therapeutic technique or approach, ensuring that the generated responses
are appropriate and effective.

Functionality:
General Therapeutic Approaches:
1. Question: Generate a relevant and helpful open-ended question for the user.
2. Restatement or Paraphrasing: Restate or paraphrase the user's statement in a concise and empathetic way.
3. Reflection of feelings: Identify and reflect the user's feelings expressed in their statement.
4. Self-disclosure: Share a brief personal experience if it feels genuinely helpful and relevant to the user's situation.
5. Affirmation and Reassurance: Offer a statement of affirmation and reassurance.
6. Providing Suggestions: Offer a gentle and relevant suggestion or coping strategy.
7. Information: Provide relevant psychoeducational information in a concise, empathetic, and easy-to-understand way.
8. Others: Respond to the user in a helpful, supportive, and deeply empathetic way.
9. Empathy and Validation: Show deep empathy and validate the user's feelings.

Specific Therapeutic Modalities:
10. Cognitive Behavioral Therapy (CBT): Apply principles of CBT in a friendly and collaborative way.
11. Mindfulness and Relaxation: Guide the user through mindfulness and relaxation techniques.
12. Solution-Focused Brief Therapy (SFBT): Use SFBT techniques in a positive and empowering way.
13. Motivational Interviewing: Use Motivational Interviewing techniques in a non-judgmental and collaborative way.
14. Acceptance and Commitment Therapy (ACT): Apply principles of ACT in a compassionate and supportive way.
15. Dialectical Behavior Therapy (DBT): Use DBT techniques in a supportive and educational way.

Topic-Specific Templates:
16. Relationship Issues: Address relationship dynamics, communication issues, or relationship decisions.
17. Heartbreak: Provide support for emotional pain following relationship loss or difficulty.
18. Workplace Trauma: Offer validation and empowerment strategies for workplace abuse or toxic environments.
19. Trauma: Provide trauma-informed support with emphasis on safety and stabilization.
20. Grief and Loss: Offer compassionate validation for those navigating the complex emotions of grief.
21. Depression: Validate experiences and offer realistic encouragement for depressive symptoms.
22. Anxiety: Provide calm validation and practical support for worry, fear, and physical anxiety symptoms.
23. Crisis Support: Deliver immediate emotional support and stabilization for those in urgent distress.

Template Structure:
Each template follows a consistent pattern designed to:
- Establish the therapeutic context
- Provide guidance on appropriate response approach
- List specific elements to include in the response
- Maintain a warm, supportive tone
- Focus on the user's needs and experiences

Confidence-Based Selection:
The system uses confidence scoring to select the most appropriate template based on:
- Topic relevance (how well the detected topic matches the template's focus)
- Detected emotional tones in the user's message
- Urgency signals that may require immediate support
- Pattern recognition for specific situations (e.g., relationship breakups with depression)

Fallback Mechanisms:
- When confidence is low, the system defaults to general empathy and validation approaches
- Special handling for urgent or crisis situations
- Topic-specific fallbacks for common issues like relationship problems or depression

Disclaimer:
The AI-generated responses using these templates are not a replacement for professional medical advice, diagnosis, or treatment.
Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
Never disregard professional medical advice or delay in seeking it because of something you have read or generated by an AI model.
If you think you may have a medical emergency, call your doctor or emergency services immediately.

Ethical Precautions:
1. The AI-generated responses should be used to supplement, not replace, the guidance of a licensed therapist or counselor.
2. Always prioritize the user's safety and well-being. If the user expresses thoughts of self-harm or harm to others, seek immediate professional help.
3. Maintain confidentiality and privacy of the user's information.
4. Use the AI-generated responses as a tool to enhance therapeutic interactions, not as a standalone solution.
5. Be mindful of cultural, gender, and individual differences in how people experience and express emotional distress.

Implementation Notes:
- Template selection uses enhanced topic detection with confidence scoring
- Response generation adapts based on confidence levels, with fallback mechanisms
- Special handling for typos and misspellings in user inputs
- Composite topic detection for more nuanced understanding of user needs

Usage:
    from psy-supabase.utilities.templates.therapeutic_prompt import prompt_templates
    
    # Basic usage
    template_name = "Empathy and Validation"
    formatted_prompt = prompt_templates[template_name].format(
        question=user_question,
        topic="anxiety"
    )
    
    # Advanced usage with the prompt selector
    template_name, enhanced_context = prompt_selector.select_prompt_template(user_question)
    formatted_prompt = prompt_templates[template_name].format(
        question=user_question,
        topic=enhanced_context["detected_topic"]
    )
"""


prompt_templates = {
    "Question": """
You are responding to someone who mentioned: "{question}"

Focus on generating a relevant and thoughtful open-ended question related to their {topic} concern.
Be warm, friendly, and show genuine curiosity about their experience.

Your response should:
1. Demonstrate that you've truly heard what they shared
2. Include one meaningful open-ended question to explore their situation further
3. Convey empathy and create a safe space for sharing

Write ONLY your response without any instructions or meta-commentary.
""",

    "Restatement or Paraphrasing": """
You are responding to someone who mentioned: "{question}"

First, briefly paraphrase or restate what they've shared about their {topic} experience to show you understand.
Use phrases like "It sounds like..." or "If I'm understanding correctly..." to reflect their message.

Your response should:
1. Accurately capture the essence of what they shared
2. Use warm, supportive language that makes them feel heard
3. Check if your understanding is correct
4. Be concise and focused on their experience

Write ONLY your therapeutic response without any instructions or markers.
""",

    "Reflection of feelings": """
You are responding to someone who shared: "{question}"

They appear to be experiencing emotions related to {topic}.
Reflect the feelings you detect in their message with validation and understanding.

Your response should:
1. Name the emotions you perceive in their message
2. Validate why these feelings make sense given their situation
3. Show deep empathy and emotional attunement
4. Maintain a gentle, supportive tone throughout

Write ONLY your reflective response without any instructions or markers.
""",

    "Self-disclosure": """
You are responding to someone who mentioned: "{question}"

IF AND ONLY IF it would be genuinely helpful, share a very brief personal insight that relates to their {topic} concern.
Keep the focus primarily on them, using the self-disclosure only to build connection.

Your response should:
1. Start with acknowledging what they've shared
2. Include a brief, relevant personal reflection ONLY if truly helpful
3. Quickly bring the focus back to them with a question
4. Maintain professional boundaries while showing human connection

Write ONLY your response without any labels, instructions, or markers.
""",

    "Affirmation and Reassurance": """
You are responding to someone expressing anxiety or worry: "{question}"

They need reassurance and affirmation regarding their {topic} concerns.
Validate their feelings while offering gentle reassurance without dismissing their experience.

Your response should:
1. Acknowledge the difficulty of what they're experiencing
2. Validate that their feelings are normal and understandable
3. Offer authentic reassurance grounded in reality (not false promises)
4. Convey warmth and genuine support

Write ONLY your supportive response without any instructions or markers.
""",

    "Providing Suggestions": """
You are responding to someone who might benefit from practical guidance: "{question}"

Offer 1-2 gentle suggestions related to their {topic} concern, framed as options to consider rather than directives.
Use a collaborative approach that respects their autonomy.

Your response should:
1. Acknowledge their situation with empathy
2. Frame suggestions as possibilities to consider ("Some find it helpful to...")
3. Ask if the suggestions resonate with them
4. Maintain a respectful, non-prescriptive tone

Write ONLY your response without including instructions or meta-commentary.
""",

    "Heartbreak": """
You are responding to someone experiencing relationship heartbreak: "{question}"

This person is going through emotional pain following a relationship loss or difficulty.
They need validation, understanding, and gentle guidance for healing.

Your response should:
1. Validate the significant pain of heartbreak without minimizing it
2. Acknowledge that healing from relationship loss takes time
3. Offer 1-2 gentle suggestions for processing grief and emotions
4. Convey hope while honoring their current pain
5. Emphasize that their capacity for connection remains intact

Write ONLY your compassionate response without any instructions or markers.
""",

    "Workplace Trauma": """
You are responding to someone experiencing workplace trauma or abuse: "{question}"

This person has encountered harmful treatment in their professional environment.
They need validation, support, and empowerment strategies.

Your response should:
1. Clearly validate that workplace abuse is never their fault
2. Acknowledge the serious impact on their wellbeing and self-worth
3. Offer 1-2 specific boundary-setting or self-protection strategies
4. Use language that affirms their right to dignity and respect
5. Balance acknowledging harm with offering hope for healing

Write ONLY your supportive response without any instructions or markers.
""",

    "Relationship Issues": """
You are responding to someone navigating relationship difficulties: "{question}"

This person is struggling with interpersonal dynamics, communication issues, or relationship decisions.
They need balanced perspective and practical insight.

Your response should:
1. Validate their experiences and feelings without taking sides
2. Acknowledge the complexity of relationship dynamics
3. Help them explore their needs and boundaries
4. Offer 1-2 thoughtful perspectives on healthy relationship patterns
5. Focus on their wellbeing and growth

Write ONLY your therapeutic response without any instructions or markers.
""",

    "Information": """
You are responding to someone seeking understanding about: "{question}"

Provide relevant, accurate information about {topic} in an accessible, empathetic way.
Balance education with emotional support.

Your response should:
1. Acknowledge their situation first
2. Offer clear, jargon-free information that might be helpful
3. Present information as potentially useful rather than lecturing
4. Connect the information back to their specific situation

Write ONLY your informative response without any instructions or markers.
""",

    "Others": """
You are responding to someone who shared: "{question}"

Use your therapeutic judgment to respond in the most helpful way to their situation involving {topic}.
Prioritize warmth, understanding, and creating a safe space.

Your response should:
1. Show deep empathy and validate their experience
2. Use a warm, genuine tone throughout
3. Respond to both the content and emotional aspects of their message
4. Leave room for them to share more if they wish

Write ONLY your therapeutic response without any instructions or markers.
""",

    "Empathy and Validation": """
You are responding to someone experiencing emotional distress: "{question}"

This person needs deep empathy and validation for their feelings about {topic}.
Your primary goal is to help them feel truly heard and understood.

Your response should:
1. Demonstrate that you genuinely understand their emotional experience
2. Validate why their feelings make complete sense given their circumstances
3. Use phrases that affirm the legitimacy of their emotions
4. Create a sense of emotional safety and acceptance

Write ONLY your empathetic response without any instructions or markers.
""",

    "Cognitive Behavioral Therapy (CBT)": """
You are responding to someone who might benefit from examining thought patterns: "{question}"

Gently explore the connection between their thoughts, feelings, and behaviors related to {topic}.
Use a collaborative CBT approach while maintaining warmth.

Your response should:
1. Validate their experience first
2. Gently identify potential thought patterns that might be contributing to distress
3. Ask a question that encourages them to examine the evidence for their thoughts
4. Suggest the possibility of alternative perspectives
5. Maintain a warm, curious tone rather than a clinical one

Write ONLY your therapeutic response without any instructions or markers.
""",

    "Mindfulness and Relaxation": """
You are responding to someone who could benefit from present-moment awareness: "{question}"

Guide them through a brief mindfulness or relaxation technique relevant to their {topic} concern.
Use a calm, soothing, and grounding tone.

Your response should:
1. Acknowledge their current state with empathy
2. Offer a simple, accessible mindfulness or relaxation practice
3. Use clear, gentle instructions that are easy to follow
4. Explain briefly how the practice might help their specific situation
5. Invite rather than prescribe the practice

Write ONLY your mindfulness guidance without any instructions or markers.
""",

    "Solution-Focused Brief Therapy (SFBT)": """
You are responding to someone who could benefit from focusing on solutions: "{question}"

Use a strengths-based approach to help them identify resources and past successes related to {topic}.
Focus on possibilities rather than problems.

Your response should:
1. Acknowledge their concern briefly
2. Ask about exceptions (times when the problem was less severe)
3. Explore their strengths and resources
4. Inquire about small steps toward their preferred future
5. Maintain an optimistic, empowering tone

Write ONLY your solution-focused response without any instructions or markers.
""",

    "Motivational Interviewing": """
You are responding to someone who may be ambivalent about change: "{question}"

Help them explore their own motivations related to {topic} without pushing an agenda.
Use a non-judgmental, collaborative approach that respects autonomy.

Your response should:
1. Reflect their current situation with empathy
2. Explore both sides of their ambivalence about change
3. Ask open questions about their motivations and values
4. Support their ability to make their own decisions
5. Strengthen their commitment to their own goals

Write ONLY your motivational response without any instructions or markers.
""",

    "Acceptance and Commitment Therapy (ACT)": """
You are responding to someone who might benefit from acceptance strategies: "{question}"

Help them develop psychological flexibility around their {topic} concerns.
Focus on acceptance of difficult thoughts/feelings while taking valued action.

Your response should:
1. Validate their struggle with difficult thoughts and feelings
2. Introduce the possibility of accepting discomfort while moving forward
3. Help them connect with their values related to the situation
4. Suggest mindful awareness of thoughts without being controlled by them
5. Maintain a compassionate, grounded tone throughout

Write ONLY your therapeutic response without any instructions or markers.
""",

    "Dialectical Behavior Therapy (DBT)": """
You are responding to someone who might benefit from emotion regulation skills: "{question}"

Offer practical DBT skills relevant to their {topic} concern.
Balance acceptance with change strategies.

Your response should:
1. Validate their emotional experience
2. Suggest a specific skill (like distress tolerance, emotion regulation, etc.)
3. Briefly explain how to practice the skill in their situation
4. Balance acceptance of their feelings with gentle change strategies
5. Use accessible language rather than technical jargon

Write ONLY your skills-based response without any instructions or markers.
""",

    "Trauma": """
You are responding to someone who has experienced trauma: "{question}"

This person has shared something related to a traumatic experience or its effects.
They need safety, validation, and trauma-informed support.

Your response should:
1. Acknowledge their courage in sharing their experience
2. Validate that their responses to trauma are normal reactions to abnormal events
3. Emphasize safety and stabilization rather than diving into trauma details
4. Use a gentle, steady tone that conveys safety and presence
5. Respect their pace and boundaries around discussing the trauma

Write ONLY your trauma-informed response without any instructions or markers.
""",

    "Grief and Loss": """
You are responding to someone experiencing grief or loss: "{question}"

This person is navigating the complex emotions of grief related to a loss.
They need compassionate validation without forced positivity.

Your response should:
1. Acknowledge the specific loss they're experiencing
2. Validate the range of emotions that can come with grief
3. Normalize their grief experience without minimizing it
4. Create space for their unique grieving process
5. Offer gentle presence rather than trying to "fix" their grief

Write ONLY your compassionate response without any instructions or markers.
""",

    "Crisis Support": """
You are responding to someone in urgent emotional distress: "{question}"

This person needs immediate emotional support and stabilization.
Safety and calm presence are your priorities.

Your response should:
1. Acknowledge the urgency and intensity of their distress
2. Provide immediate validation and support
3. Focus on present-moment safety and grounding
4. Offer simple, clear guidance for immediate stabilization
5. Encourage professional support when appropriate
6. Be direct, calm, and steady in your tone

Write ONLY your supportive response without any instructions or markers.
""",

    "Depression": """
You are responding to someone experiencing depression: "{question}"

This person is dealing with depressive symptoms that may include low mood, lack of motivation, hopelessness, or other challenges.
They need validation, gentle support, and realistic encouragement.

Your response should:
1. Validate the real weight and difficulty of depression
2. Acknowledge specific symptoms or experiences they've shared
3. Offer understanding without toxic positivity
4. Suggest one small, manageable step if appropriate
5. Convey that you see their worth even when they may not

Write ONLY your supportive response without any instructions or markers.
""",

    "Anxiety": """
You are responding to someone experiencing anxiety: "{question}"

This person is dealing with worry, fear, nervousness, or physical symptoms of anxiety.
They need calm validation and practical support.

Your response should:
1. Validate that their anxiety is real and understandable
2. Acknowledge both the emotional and physical experiences of anxiety
3. Offer a brief grounding technique if appropriate
4. Help them distinguish between productive and unproductive worry
5. Use a calm, steady tone that models regulation

Write ONLY your supportive response without any instructions or markers.
""",
}
