""" Utility functions for therapeutic mappings. """

from typing import Any, Dict, Final, List, Optional, Tuple


class TherapeuticMappings:
    """Centralized therapeutic mappings for consistent theme/keyword handling."""

    ENHANCED_TAXONOMY: Dict[str, List[str]] = {
        "depression": [
            "melancholy",
            "fatigue",
            "tired",
            "unmotivated",
            "don't enjoy",
            "insomnia",
            "exhausted",
            "weight",
            "can't sleep",
            "appetite",
            "guilt",
            "concentration",
            "depressed",
            "no motivation",
            "unhappy",
            "empty",
            "suicidal",
            "no energy",
            "no interest",
            "lost interest",
            "sad",
            "hypersomnia",
            "indecisive",
            "numb",
            "anhedonia",
            "can't eat",
            "psychomotor",
            "can't enjoy",
            "worthless",
            "gloomy",
            "despair",
            "miserable",
            "emptiness",
            "meaningless",
            "depression",
            "hopeless",
        ],
        "anxiety": [
            "nervous",
            "on edge",
            "frightened",
            "catastrophizing",
            "dread",
            "arousal",
            "apprehensive",
            "overwhelmed",
            "anxious",
            "racing thoughts",
            "uneasy",
            "hypervigilant",
            "stress",
            "panic",
            "worry",
            "social anxiety",
            "scared",
            "obsessive",
            "avoidance",
            "tense",
            "irritable",
            "fear",
            "restless",
            "compulsive",
            "phobia",
            "worried",
            "anxiety",
            "overthinking",
            "performance anxiety",
        ],
        "trauma": [
            "neglect",
            "avoidance",
            "nightmare",
            "trauma",
            "violence",
            "hyperarousal",
            "harass",
            "ptsd",
            "assaulted",
            "startle",
            "horror",
            "childhood trauma",
            "threat",
            "helpless",
            "assault",
            "intrusion",
            "flashback",
            "emotional dysregulation",
            "survivor",
            "accident",
            "danger",
            "numb",
            "triggered",
            "traumatized",
            "dissociate",
            "disaster",
            "victim",
            "abuse",
            "hypervigilant",
            "abused",
            "victimized",
            "detached",
        ],
        # workplace trauma and abuse
        "workplace_trauma": [
            # Primary workplace abuse terms (stronger matches)
            "workplace abuse",
            "work abuse",
            "boss abuse",
            "manager abuse",
            "toxic workplace",
            "hostile work",
            "bullied at work",
            "harassed at work",
            "workplace harassment",
            "workplace bullying",
            "abused at work",
            "work trauma",
            "workplace trauma",
            "toxic boss",
            "toxic manager",
            "abusive supervisor",
            "boss bully",
            "manager bully",
            "workplace bully",
            # Secondary workplace terms
            "mobbing",
            "work stress",
            "threatened at work",
            "intimidated at work",
            "humiliated at work",
            "workplace retaliation",
            "work mistreatment",
            "gaslighting at work",
            "workplace injustice",
            "unfair treatment at work",
            # Additional workplace problem indicators
            "discriminated at work",
            "work discrimination",
            "hostile environment",
            "career sabotage",
            "workplace violence",
            "demotion",
            "unfair review",
            "fired unfairly",
            "targeted at work",
            "work anxiety",
            "job trauma",
            "toxic team",
            "toxic coworker",
            "work harassment",
            "work bullying",
            # Common phrases
            "hate my job",
            "hate my boss",
            "terrible workplace",
            "awful job",
            "hostile boss",
            "mean coworker",
            "being bullied",
            "being harassed",
            "work is hell",
            "office politics",
            "power abuse",
            "authority abuse",
            "work ptsd",
            "verbally abused",
            "yelled at",
            "screamed at",
        ],
        # Relationship-related topics
        "relationship": [
            "relationship",
            "marriage",
            "partner",
            "boyfriend",
            "girlfriend",
            "husband",
            "wife",
            "spouse",
            "couple",
            "dating",
            "significant other",
            "ex",
            "breakup",
            "divorce",
            "separated",
            "together",
            "commitment",
            "trust",
            "betrayal",
            "cheating",
            "infidelity",
            "jealousy",
            "communication",
            "argument",
            "fight",
            "romantic",
            "love",
            "loved",
            "loving",
            "connection",
            "attachment",
        ],
        # heartbreak and healing
        "heartbreak": [
            "heartbreak",
            "heartbroken",
            "broken heart",
            "broken up",
            "dumped",
            "rejected",
            "betrayed",
            "abandoned",
            "alone",
            "lonely",
            "miss them",
            "missing them",
            "moving on",
            "get over",
            "heal",
            "healing",
            "closure",
            "broken heart",
            "love pain",
            "hurt by love",
            "hurt by them",
            "never again",
            "brake my heart",
            "break my heart",
            "no more love",
            "trust again",
            "never trust",
            "fall in love",
            "falling for someone",
            "vulnerable",
        ],
        "interpersonal": [
            "relationship",
            "marriage",
            "partner",
            "spouse",
            "family",
            "friend",
            "colleague",
            "conflict",
            "intimacy",
            "attachment",
            "boundary",
            "communication",
            "trust",
            "abandonment",
            "rejection",
            "loneliness",
            "isolation",
            "connection",
            "breakup",
            "divorce",
            "separation",
            "betrayal",
            "argument",
            "misunderstanding",
        ],
        "identity": [
            "self-esteem",
            "identity",
            "self-worth",
            "confidence",
            "imposter",
            "shame",
            "perfectionism",
            "failure",
            "inadequacy",
            "self-doubt",
            "body image",
            "self-criticism",
            "self-compassion",
            "validation",
            "purpose",
            "meaning",
            "values",
            "authentic",
            "true self",
            "gender",
            "sexuality",
            "culture",
        ],
        "adjustment": [
            "grief",
            "loss",
            "bereavement",
            "change",
            "transition",
            "adaptation",
            "adjustment",
            "stress",
            "coping",
            "resilience",
            "life stage",
            "retirement",
            "career",
            "moving",
            "relocation",
            "major life event",
            "crisis",
            "upheaval",
            "uncertainty",
            "decision-making",
            "crossroads",
            "opportunity",
            "challenge",
        ],
        "behavior": [
            "addiction",
            "substance",
            "alcohol",
            "drug",
            "gambling",
            "compulsive",
            "habit",
            "dependence",
            "withdrawal",
            "craving",
            "relapse",
            "recovery",
            "abstinence",
            "moderation",
            "harm-reduction",
            "impulse control",
            "self-regulation",
            "behavioral therapy",
            "reinforcement",
            "trigger",
        ],
        "wellness": [
            "mindfulness",
            "meditation",
            "relaxation",
            "self-care",
            "resilience",
            "growth",
            "strength",
            "resource",
            "wellness",
            "prevention",
            "maintenance",
            "balance",
            "harmony",
            "fulfillment",
            "joy",
            "satisfaction",
            "gratitude",
            "meaning",
            "purpose",
            "flourishing",
            "thriving",
            "vitality",
        ],
        "cognition": [
            "thought",
            "belief",
            "cognition",
            "distortion",
            "schema",
            "assumption",
            "automatic thought",
            "rumination",
            "worry",
            "attention",
            "memory",
            "concentration",
            "problem-solving",
            "decision-making",
            "perception",
            "interpretation",
            "reframe",
            "perspective",
            "mindset",
            "attribution",
        ],
        "grief_loss": [
            "bereavement",
            "loss",
            "mourning",
            "acceptance",
            "denial",
            "anger",
            "bargaining",
            "depression",
            "adaptation",
            "adjustment",
            "memorialization",
            "letting go",
            "moving on",
            "honoring",
            "memory",
        ],
        "self-compassion": [
            "self-kindness",
            "common humanity",
            "mindfulness",
            "self-criticism",
            "self-care",
            "forgiveness",
            "acceptance",
            "compassionate voice",
            "inner peace",
            "empathy",
        ],
        "guilt": [
            "guilt",
            "guilty",
            "regret",
            "wrongdoing",
            "redemption",
            "forgiveness",
            "moral distress",
            "self-forgiveness",
            "conscience",
            "remorse",
            "apologize",
            "sorry",
        ],
        "shame": [
            "shame",
            "ashamed",
            "humiliation",
            "embarrassment",
            "mortified",
            "self-conscious",
            "inadequate",
            "unworthy",
            "defective",
            "flawed",
            "exposed",
            "inferior",
            "self-judgment",
            "self-blame",
        ],
        "obsessive_compulsive_disorder": [
            "obsession",
            "compulsion",
            "ritual",
            "perfectionism",
            "control",
            "anxiety",
            "reassurance-seeking",
            "intrusive thought",
            "cleaning",
            "checking",
            "counting",
            "hoarding",
        ],
        "suicidality_self_harm": [
            "suicidal",
            "self-harm",
            "cutting",
            "despair",
            "hopelessness",
            "crisis",
            "emotional pain",
            "coping",
            "prevention",
            "life-threatening",
            "overwhelming",
        ],
        "emotional_support": ["help", "support", "understand", "listen", "care", "concern"],
    }

    THERAPEUTIC_THEMES: Dict[str, Dict[str, Any]] = {
        "abandonment": {
            "keywords": ["abandon", "left me", "alone", "desert"],
            "approach": "abandonment",
            "template": "attachment_based_therapy",
            "human_readable": "abandonment_support",
        },
        "rejection": {
            "keywords": ["reject", "unwanted", "excluded", "cast aside"],
            "approach": "self-compassion",
            "template": "empathy_validation",
            "human_readable": "rejection_support",
        },
        "control": {
            "keywords": ["control", "helpless", "powerless", "manipulation"],
            "approach": "cbt",
            "template": "cognitive_behavioral_therapy",
            "human_readable": "control_support",
        },
        "anxiety": {
            "keywords": ["anxiety", "anxious", "worry", "panic", "nervous", "stress"],
            "approach": "cbt",
            "template": "cognitive_behavioral_therapy",
            "human_readable": "anxiety",
        },
        "depression": {
            "keywords": ["depression", "depressed", "sad", "unmotivated", "hopeless"],
            "approach": "behavioral_activation",
            "template": "depression",
            "human_readable": "depression_support",
        },
        "relationship": {
            "keywords": [
                "relationship",
                "breakup",
                "partner",
                "husband",
                "wife",
                "girlfriend",
                "boyfriend",
                "friend",
                "family",
            ],
            "approach": "interpersonal_therapy",
            "template": "relationship_issues",
            "human_readable": "relationship_guidance",
        },
        "self-worth": {
            "keywords": [
                "worthless",
                "undeserving",
                "inadequate",
                "unworthy",
                "failure",
                "confidence",
                "self-esteem",
                "worth",
            ],
            "approach": "self-compassion",
            "template": "empathy_validation",
            "human_readable": "self-worth-enhancement",
        },
        "trauma": {
            "keywords": ["trauma", "ptsd", "flashback", "abuse", "assault"],
            "approach": "trauma",
            "template": "trauma",
            "human_readable": "trauma_support",
        },
        "loneliness": {
            "keywords": ["lonely", "alone", "isolated", "connection", "abandoned", "desert"],
            "approach": "connection_building",
            "template": "others",
            "human_readable": "connection_building",
        },
        "grief": {
            "keywords": ["grief", "loss", "death", "died"],
            "approach": "grief_processing",
            "template": "grief_loss",
            "human_readable": "grief_processing",
        },
        "trust": {
            "keywords": ["trust", "betrayal", "suspicious", "faith", "rely"],
            "approach": "interpersonal_therapy",
            "template": "relationship_issues",
            "human_readable": "trust_building",
        },
        "emotional_regulation": {
            "keywords": ["overwhelm", "regulate", "emotion", "feelings", "manage"],
            "approach": "dbt",
            "template": "dialectical_behavior_therapy",
            "human_readable": "emotional_regulation",
        },
        "guilt": {
            "keywords": [
                "feel guilty",
                "guilt",
                "remorse",
                "feeling guilty",
                "guilt about",
                "guilty about",
                "regret doing",
                "wrongdoing",
                "did something wrong",
            ],
            "approach": "self-compassion",
            "template": "guilt",
            "human_readable": "Guilt Processing",
        },
        "shame": {
            "keywords": [
                "feel ashamed",
                "feeling ashamed",
                "shame about",
                "ashamed of",
                "embarrassment",
                "humiliated",
                "humiliation",
                "embarrassed",
                "feel worthless",
                "feel defective",
                "feel inadequate",
            ],
            "approach": "self-compassion",
            "template": "shame",
            "human_readable": "Shame Processing",
        },
        "workplace_anxiety": {
            "keywords": ["work", "job", "career", "boss", "workplace", "office", "coworker", "colleague"],
            "approach": "cognitive_behavioral",
            "template": "cognitive_behavioral_therapy",
            "human_readable": "Workplace Anxiety Support",
        },
    }

    APPROACH_TO_TEMPLATE = {
        "cbt": "cognitive_behavioral_therapy",
        "behavioral_activation": "depression",
        "interpersonal_therapy": "relationship_issues",
        "self-compassion": "empathy_validation",
        "trauma": "trauma",
        "connection_building": "others",
        "grief_processing": "grief_loss",
        "supportive_listening": "empathy_validation",
        "dbt": "dialectical_behavior_therapy",
        "abandonment": "attachment_based_therapy",
        "anxiety": "cognitive_behavioral_therapy",
        "mindfulness": "mindfulness_relaxation",
        "crisis": "crisis_support",
        "workplace": "workplace_trauma",
        "heartbreak": "heartbreak",
        "information": "information",
        "acceptance": "acceptance_commitment_therapy",
        "sfbt": "solution_focused_brief_therapy",
        "motivational": "motivational_interviewing",
        "empathy_validation": "empathy_validation",
        "others": "others",
        "depression": "depression",
        "grief_loss": "grief_loss",
        "grief_reflection": "grief_loss",
        "self-criticism": "self-compassion",
        "guilt": "guilt",
        "shame": "shame",
        "ocd": "obsessive_compulsive_disorder",
        "suicidality_self_harm": "suicidality_self_harm",
        "emotional_support": "emotional_support",
        "workplace_trauma": "workplace_trauma",
        "identity": "identity",
        "adjustment": "adjustment",
        "behavior": "behavior",
        "wellness": "wellness",
        "cognition": "cognition",
        "emotional_regulation": "emotional_regulation",
        "self-worth": "self-worth",
        "relationship": "relationship_issues",
        "interpersonal": "interpersonal_therapy",
        "self-esteem": "self-compassion",
    }

    EMOTION_PATTERNS: Final[Dict[str, List[Tuple[str, float]]]] = {
        "sadness": [
            (r"\bsad(ness)?\b", 2.0),
            (r"\bdown\b", 2.0),
            (r"\bunhappy\b", 1.5),
            (r"\bempty\b", 1.8),
            (r"\btear(s|ful)?\b", 1.5),
            (r"\bcry(ing)?\b", 1.5),
            (r"\bgrief\b", 2.0),
            (r"\bloss\b", 1.5),
            (r"\bheartbroken\b", 2.0),
            (r"\bmiserable\b", 1.5),
            (r"\bdepressed\b", 2.0),
            (r"\bhopeless\b", 1.5),
            (r"\bworthless\b", 1.5),
        ],
        "shame": [
            (r"\bashamed\b", 2.2),
            (r"\bshame\b", 2.0),
            (r"\bhumiliated\b", 1.8),
            (r"\bmortified\b", 1.8),
            (r"\bself-conscious\b", 1.5),
            (r"\binadequate\b", 1.5),
            (r"\bflawed\b", 1.5),
            (r"\bdefective\b", 1.5),
        ],
        "guilt": [
            (r"\bguilt(y)?\b", 2.0),
            (r"\bremorse\b", 1.8),
            (r"\bregret\b", 1.8),
            (r"\bsorry\b", 1.5),
            (r"\bapologetic\b", 1.5),
            (r"\bwrongdoing\b", 1.5),
            (r"\bself[- ]?blame\b", 1.5),
            (r"\bembarrass(ed|ment)?\b", 1.2),
        ],
        "anxiety": [
            # Standard patterns - with higher weight (2.0)
            (r"\banxiety\b", 2.0),
            (r"\banxious\b", 2.0),
            (r"\bpanic\b", 2.0),
            (r"\bworried\b", 1.8),
            (r"\bfear\b", 1.8),
            (r"\bstress(ed)?\b", 1.5),
            (r"\boverwhelm(ed|ing)\b", 1.5),
            # Subtle patterns
            (r"\bwhat (might|could) go wrong\b", 2.3),
            (r"\bconstantly worry\b", 1.5),
            (r"\bnervous\b", 1.5),
            (r"\bon edge\b", 1.5),
            (r"\bcan\'t relax\b", 1.5),
            (r"\brestless\b", 1.2),
            (r"\buneasy\b", 1.2),
            (r"\btense\b", 1.2),
            (r"\bworry about\b", 1.8),
            (r"\banxious about\b", 2.0),
        ],
        "depression": [
            # Standard patterns
            (r"\bdepress(ed|ion)\b", 2.0),
            (r"\bsad\b", 1.8),
            (r"\blow\b", 1.2),
            (r"\bmood\b", 1.0),
            (r"\bhopeless\b", 1.8),
            (r"\bunmotivated\b", 1.5),
            (r"\bexhausted\b", 1.2),
            # Subtle patterns
            (r"\bdon\'t enjoy\b", 1.5),
            (r"\bno pleasure\b", 1.5),
            (r"\blost interest\b", 1.5),
            (r"\bno energy\b", 1.2),
            (r"\bfeel empty\b", 1.5),
            (r"\bworthless\b", 1.8),
            (r"\btired all the time\b", 1.2),
            (r"\bfeeling down\b", 1.5),
        ],
        "trauma": [
            (r"\btrauma\b", 2.0),
            (r"\bptsd\b", 2.0),
            (r"\babuse\b", 1.8),
            (r"\bviolent\b", 1.5),
            (r"\bassault\b", 1.8),
            (r"\bincident\b", 1.0),
            (r"\bflashbacks\b", 1.8),
            (r"\bnightmares\b", 1.5),
            (r"\bhaunt\b", 1.2),
        ],
        "relationships": [
            (r"\bpartner\b", 1.5),
            (r"\bspouse\b", 1.5),
            (r"\bmarriage\b", 1.8),
            (r"\brelationship\b", 2.0),
            (r"\bdating\b", 1.5),
            (r"\bcouple\b", 1.2),
            (r"\bex\b", 1.3),
            (r"\bbreak[- ]?up\b", 1.8),
            (r"\bgirlfriend\b", 1.5),
            (r"\bboyfriend\b", 1.5),
            (r"\bhusband\b", 1.5),
            (r"\bwife\b", 1.5),
            (r"\bdivorce\b", 1.8),
            (r"\bseparation\b", 1.5),
        ],
        "self-esteem": [
            (r"\bself[- ]esteem\b", 2.0),
            (r"\bconfidence\b", 1.8),
            (r"\bworth\b", 1.5),
            (r"\bunlovable\b", 1.8),
            (r"\bunattractive\b", 1.5),
            (r"\binadequate\b", 1.8),
            (r"\bnot good enough\b", 2.0),
            (r"\bnever feel good enough\b", 2.0),
            (r"\bfailure\b", 1.8),
            (r"\bworthless\b", 1.8),
            (r"\bhate myself\b", 2.0),
            (r"\bugly\b", 1.5),
            (r"\bcompared to others\b", 1.8),
        ],
        "stress": [
            (r"\bstress(ed)?\b", 1.8),
            (r"\boverwhelm(ed|ing)\b", 1.8),
            (r"\bbusy\b", 1.0),
            (r"\bworkload\b", 1.5),
            (r"\bburn[- ]?out\b", 1.8),
            (r"\bcoping\b", 1.2),
            (r"\btoo much to do\b", 1.5),
            (r"\boverworked\b", 1.8),
        ],
        "identity": [
            (r"\bidentity\b", 1.8),
            (r"\bwho am I\b", 1.8),
            (r"\bmeaning\b", 1.5),
            (r"\bpurpose\b", 1.5),
            (r"\bdirection\b", 1.2),
            (r"\blife purpose\b", 1.8),
            (r"\bexistential\b", 1.8),
        ],
        "loneliness": [
            (r"\blonely\b", 2.0),
            (r"\balone\b", 1.8),
            (r"\bisolat(ed|ion)\b", 1.8),
            (r"\bno friends\b", 2.0),
            (r"\bsocially\b", 1.0),
            (r"\bconnection\b", 1.2),
            (r"\bno one\b", 1.5),
            (r"\bsolitude\b", 1.5),
        ],
        "fear": [
            (r"\bfear(ful)?\b", 2.0),
            (r"\bscared\b", 2.0),
            (r"\bafraid\b", 2.0),
            (r"\bterrified\b", 2.0),
            (r"\banxious\b", 2.0),
            (r"\banxiety\b", 2.0),
            (r"\bnervous\b", 1.5),
            (r"\bpanic\b", 2.0),
            (r"\bworry(ing)?\b", 1.5),
            (r"\boverwhelm(ed|ing)?\b", 1.5),
            (r"\buneasy\b", 1.2),
            (r"\btense\b", 1.2),
            (r"\bwon\'t work out\b", 1.8),
        ],
        "anger": [
            (r"\bangry\b", 2.0),
            (r"\banger\b", 2.0),
            (r"\bfrustrat(ed|ion)?\b", 1.8),
            (r"\bfurious\b", 2.5),
            (r"\birritat(ed|ion)?\b", 1.5),
            (r"\brage\b", 2.0),
            (r"\bmad\b", 1.5),
            (r"\bannoy(ed|ing)?\b", 1.2),
            (r"\bresent(ment)?\b", 1.5),
            (r"\bfed up\b", 2.3),
        ],
        "joy": [
            (r"\bhappy\b", 2.0),
            (r"\bjoy(ful)?\b", 2.0),
            (r"\bthrilled\b", 2.5),
            (r"\bgood news\b", 2.0),
            (r"\bexcited\b", 1.8),
            (r"\bcontent\b", 1.2),
            (r"\bgrateful\b", 1.2),
            (r"\bpleased\b", 1.2),
            (r"\boptimistic\b", 1.2),
            (r"\bhopeful\b", 1.2),
        ],
        "love": [
            (r"\blove\b", 2.0),
            (r"\bloved\b", 2.0),
            (r"\bcared\b", 1.5),
            (r"\bcaring\b", 1.2),
            (r"\baffection\b", 1.2),
            (r"\bconnected\b", 1.2),
            (r"\bclose\b", 1.2),
        ],
        "disgust": [
            (r"\bdisgust(ed|ing)?\b", 2.0),
            (r"\brepuls(ed|ion)?\b", 1.5),
            (r"\baversion\b", 1.2),
        ],
        "surprise": [
            (r"\bsurpris(ed|ing)?\b", 2.5),
            (r"\bhow things turned out\b", 2.0),
            (r"\bshocked\b", 1.5),
            (r"\bamazed\b", 1.2),
            (r"\bstunned\b", 1.2),
        ],
        "confusion": [
            (r"\bconfus(ed|ion)?\b", 2.0),
            (r"\buncertain\b", 1.5),
            (r"\bunsure\b", 1.5),
            (r"\bdoubt\b", 1.2),
        ],
        "relief": [
            (r"\brelief\b", 2.0),
            (r"\brelieved\b", 2.0),
            (r"\bcalm\b", 1.5),
            (r"\bsoothe(d|ing)?\b", 1.2),
            (r"\bpeaceful\b", 1.2),
        ],
    }

    # 1. PURE EMOTIONS - fundamental affect states
    CORE_EMOTIONS: Final[Dict[str, List[Tuple[str, float]]]] = {
        "anger": [
            (r"\bangry\b", 2.0),
            (r"\banger\b", 2.0),
            (r"\bfrustrat(ed|ion)?\b", 1.8),
            (r"\bfurious\b", 2.5),
            (r"\birritat(ed|ion)?\b", 1.5),
            (r"\brage\b", 2.0),
            (r"\bmad\b", 1.5),
            (r"\bannoy(ed|ing)?\b", 1.2),
            (r"\bresent(ment)?\b", 1.5),
            (r"\bfed up\b", 2.3),
        ],
        "fear": [
            (r"\bfear(ful)?\b", 2.0),
            (r"\bscared\b", 2.0),
            (r"\bafraid\b", 2.0),
            (r"\bterrified\b", 2.5),
            (r"\bworried\b", 2.2),
            (r"\bnervous\b", 1.5),
            (r"\buneasy\b", 1.2),
            (r"\btense\b", 1.2),
            (r"\bwon\'t work out\b", 1.8),
        ],
        "sadness": [
            (r"\bsad(ness)?\b", 2.0),
            (r"\bdown\b", 2.2),
            (r"\bunhappy\b", 1.5),
            (r"\btear(s|ful)?\b", 1.5),
            (r"\bcry(ing)?\b", 1.5),
            (r"\bmiserable\b", 1.5),
            (r"\bheartbroken\b", 2.0),
            (r"\bempty inside\b", 2.3),
            (r"\bfeel(ing)? really down\b", 2.4),
        ],
        "shame": [
            (r"\b(feel)?(a?)shame(d)?\b", 2.5),
            (r"\bhumiliated\b", 1.8),
            (r"\bmortified\b", 1.8),
            (r"\bself-conscious\b", 1.5),
            (r"\binadequate\b", 1.5),
            (r"\bflawed\b", 1.5),
            (r"\bdefective\b", 1.5),
            (r"\bforgive myself\b", 2.4),
        ],
        "guilt": [
            (r"\bguilt(y)?\b", 2.0),
            (r"\bremorse\b", 1.5),
            (r"\bregret\b", 1.5),
            (r"\bsorry\b", 1.5),
            (r"\bapologetic\b", 1.5),
            (r"\bwrongdoing\b", 1.5),
            (r"\bself[- ]?blame\b", 1.5),
            (r"\bembarrass(ed|ment)?\b", 1.2),
        ],
        "joy": [
            (r"\bhappy\b", 2.0),
            (r"\bjoy(ful)?\b", 2.0),
            (r"\bthrilled\b", 2.5),
            (r"\bgood news\b", 2.0),
            (r"\bexcited\b", 1.8),
            (r"\bcontent\b", 1.2),
            (r"\bgrateful\b", 1.2),
            (r"\bpleased\b", 1.2),
            (r"\boptimistic\b", 1.2),
            (r"\bhopeful\b", 1.2),
        ],
        "love": [
            (r"\blove\b", 2.0),
            (r"\bloved\b", 2.0),
            (r"\bcared\b", 1.5),
            (r"\bcaring\b", 1.2),
            (r"\baffection\b", 1.2),
            (r"\bconnected\b", 1.2),
        ],
        "disgust": [
            (r"\bdisgust(ed|ing)?\b", 2.0),
            (r"\brepuls(ed|ion)?\b", 1.5),
            (r"\baversion\b", 1.2),
        ],
        "surprise": [
            (r"\bsurpris(ed|ing)?\b", 2.2),
            (r"\bshocked\b", 1.5),
            (r"\bamazed\b", 1.2),
            (r"\bstunned\b", 1.2),
        ],
        "confusion": [
            (r"\bconfus(ed|ion)?\b", 2.0),
            (r"\buncertain\b", 1.5),
            (r"\bunsure\b", 1.5),
            (r"\bdoubt\b", 1.2),
        ],
        "relief": [
            (r"\brelief\b", 2.0),
            (r"\brelieved\b", 2.0),
            (r"\bcalm\b", 1.5),
            (r"\bsoothe(d|ing)?\b", 1.2),
            (r"\bpeaceful\b", 1.2),
        ],
    }

    # 2. CLINICAL PATTERNS - clinical/diagnostic categories
    CLINICAL_PATTERNS: Final[Dict[str, List[Tuple[str, float]]]] = {
        "anxiety": [
            (r"\banxiety\b", 2.2),
            (r"\banxious\b", 2.2),
            (r"\bpanic\b", 2.0),
            (r"\bworried\b", 1.8),
            (r"\bstress(ed)?\b", 1.5),
            (r"\boverwhelm(ed|ing)\b", 1.5),
            (r"\bconstantly worry\b", 1.5),
            (r"\bon edge\b", 1.5),
            (r"\bcan\'t relax\b", 1.5),
            (r"\brestless\b", 1.2),
        ],
        "depression": [
            (r"\bdepress(ed|ion)\b", 2.0),
            (r"\blow\b", 1.2),
            (r"\bhopeless\b", 1.8),
            (r"\bunmotivated\b", 1.5),
            (r"\bexhausted\b", 1.2),
            (r"\bdon\'t enjoy\b", 1.5),
            (r"\bno pleasure\b", 1.5),
            (r"\blost interest\b", 1.5),
            (r"\bno energy\b", 1.2),
            (r"\bfeel empty\b", 1.5),
            (r"\bworthless\b", 1.8),
        ],
        "trauma": [
            (r"\btrauma\b", 2.0),
            (r"\bptsd\b", 2.0),
            (r"\babuse\b", 1.8),
            (r"\bviolent\b", 1.5),
            (r"\bassault\b", 1.8),
            (r"\bflashbacks\b", 1.8),
            (r"\bnightmares\b", 1.5),
            (r"\bhaunt\b", 1.2),
        ],
        "stress": [
            (r"\bstress(ed)?\b", 1.8),
            (r"\boverwhelm(ed|ing)\b", 1.8),
            (r"\bworkload\b", 1.5),
            (r"\bburn[- ]?out\b", 1.8),
            (r"\bcoping\b", 1.2),
            (r"\btoo much to do\b", 1.5),
            (r"\boverworked\b", 1.8),
        ],
    }

    # 3. INTERPERSONAL/IDENTITY PATTERNS - relationship and self-concept
    INTERPERSONAL_PATTERNS: Final[Dict[str, List[Tuple[str, float]]]] = {
        "relationships": [
            (r"\brelationship\b", 2.0),
            (r"\bpartner\b", 1.5),
            (r"\bspouse\b", 1.5),
            (r"\bmarriage\b", 1.8),
            (r"\bdating\b", 1.5),
            (r"\bcouple\b", 1.2),
            (r"\bbreak[- ]?up\b", 1.8),
            (r"\bdivorce\b", 1.8),
        ],
        "loneliness": [
            (r"\blonely\b", 2.0),
            (r"\balone\b", 1.8),
            (r"\bisolat(ed|ion)\b", 1.8),
            (r"\bno friends\b", 2.0),
            (r"\bconnection\b", 1.2),
            (r"\bno one\b", 1.5),
            (r"\bsolitude\b", 1.5),
        ],
        "self-esteem": [
            (r"\bself[- ]esteem\b", 2.0),
            (r"\bconfidence\b", 1.8),
            (r"\bworth\b", 1.5),
            (r"\bunlovable\b", 1.8),
            (r"\bfailure\b", 2.2),
            (r"\bworthless\b", 2.2),
            (r"\bunattractive\b", 1.5),
            (r"\binadequate\b", 1.8),
            (r"\bnot good enough\b", 2.0),
            (r"\bnever feel good enough\b", 2.0),
            (r"\bhate myself\b", 2.0),
            (r"\bugly\b", 1.5),
            (r"\bcompared to others\b", 1.8),
        ],
        "identity": [
            (r"\bidentity\b", 1.8),
            (r"\bwho am I\b", 1.8),
            (r"\bmeaning\b", 1.5),
            (r"\bpurpose\b", 1.5),
            (r"\bdirection\b", 1.2),
            (r"\blife purpose\b", 1.8),
            (r"\bexistential\b", 1.8),
        ],
    }

    @classmethod
    def get_keywords_for_theme(cls, theme: str) -> List[str]:
        """Get keywords for a specific theme."""
        return cls.THERAPEUTIC_THEMES.get(theme.lower(), {}).get("keywords", [])

    @classmethod
    def get_approach_for_theme(cls, theme: str) -> str:
        """Get therapeutic approach for a theme."""
        return cls.THERAPEUTIC_THEMES.get(theme, {}).get("approach", "supportive_listening").lower()

    @classmethod
    def get_template_for_approach(cls, approach: Optional[str] = None) -> str:
        """Get template name for a therapeutic approach."""
        if not approach:
            return "empathy_validation"
        return cls.APPROACH_TO_TEMPLATE.get(approach.lower(), "empathy_validation")

    @classmethod
    def get_template_for_theme(cls, theme: str) -> str:
        """
        Get template for a theme/topic by first getting its approach,
        then mapping approach to template.
        """
        approach = cls.get_approach_for_theme(theme)
        return cls.get_template_for_approach(approach)

    @classmethod
    def get_human_readable_name(cls, theme: str) -> str:
        """Get human-readable name for a theme."""
        return cls.THERAPEUTIC_THEMES.get(theme.lower(), {}).get("human_readable", "supportive_listening")

    @classmethod
    def get_keywords_for_taxonomy(cls, category: str) -> List[str]:
        """Get keywords for a specific taxonomy category (from enhanced taxonomy)."""
        return cls.ENHANCED_TAXONOMY.get(category.lower(), [])

    @classmethod
    def find_theme_for_keyword(cls, keyword: str) -> Optional[str]:
        """Find the appropriate theme for a given keyword using all available taxonomies."""
        if not keyword:
            return "supportive_listening"

        keyword = keyword.lower()

        # First check THERAPEUTIC_THEMES
        for theme, data in cls.THERAPEUTIC_THEMES.items():
            if any(k.lower() == keyword or keyword in k.lower() for k in data.get("keywords", [])):
                return theme

        # Then check ENHANCED_TAXONOMY
        for theme, keywords in cls.ENHANCED_TAXONOMY.items():
            if any(k.lower() == keyword or keyword in k.lower() for k in keywords):
                return theme

        return "supportive_listening"

    # @classmethod
    # def get_emotion_pattern(cls, emotion: str) -> List[Tuple[str, float]]:
    #     """Get emotion detection patterns for a specific emotion."""
    #     return cls.EMOTION_PATTERNS.get(emotion, [])

    @classmethod
    def get_all_emotion_patterns(cls) -> Dict[str, List[Tuple[str, float]]]:
        """Get all emotion detection patterns."""
        return cls.EMOTION_PATTERNS

    @classmethod
    def get_emotion_patterns(cls) -> Dict[str, List[Tuple[str, float]]]:
        """Get only pure emotion patterns for emotion detection."""
        return cls.CORE_EMOTIONS

    @classmethod
    def get_clinical_patterns(cls) -> Dict[str, List[Tuple[str, float]]]:
        """Get clinical patterns for mental health condition detection."""
        return cls.CLINICAL_PATTERNS

    @classmethod
    def get_interpersonal_patterns(cls) -> Dict[str, List[Tuple[str, float]]]:
        """Get interpersonal patterns for relationship/identity detection."""
        return cls.INTERPERSONAL_PATTERNS

    @classmethod
    def get_all_patterns(cls) -> Dict[str, List[Tuple[str, float]]]:
        """Get all patterns combined (for backward compatibility)."""
        all_patterns = {}
        all_patterns.update(cls.CORE_EMOTIONS)
        all_patterns.update(cls.CLINICAL_PATTERNS)
        all_patterns.update(cls.INTERPERSONAL_PATTERNS)
        return all_patterns
